### PR TITLE
Migrate Blob service properties related cmdlets and storage account related fixes

### PR DESCRIPTION
**Pull request by yifanz0**
## Description
This PR includes migration of Get-AzStorageBlobServiceProperty and Update-AzStorageBlobServiceProperty to Track2 SDK, and fixes of Set/New-AzStorageAccount. 

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by blueww** [comment]
@yifanz0 

I meet 14 build error with the code, would you please help to look?
You might only add part of your local change to the PR. If so, please stash your other local changes, and make sure the PR changes pass build and pass test cases.

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1503	Argument 1: cannot convert from 'Microsoft.Azure.Management.Storage.Models.RestorePolicyProperties' to 'Azure.ResourceManager.Storage.Models.RestorePolicyProperties'	Storage.Management	D:\code\PSH_Dev\src\Storage\Storage.Management\Blob\DisableAzureStorageBlobRestorePolicy.cs	117	Active
Error	CS1503	Argument 1: cannot convert from 'Microsoft.Azure.Management.Storage.Models.DeleteRetentionPolicy' to 'Azure.ResourceManager.Storage.Models.DeleteRetentionPolicy'	Storage.Management	D:\code\PSH_Dev\src\Storage\Storage.Management\Blob\EnableAzureStorageBlobDeleteRetentionPolicy.cs	124	Active
Error	CS1503	Argument 1: cannot convert from 'Microsoft.Azure.Management.Storage.Models.LastAccessTimeTrackingPolicy' to 'Azure.ResourceManager.Storage.Models.LastAccessTimeTrackingPolicy'	Storage.Management	D:\code\PSH_Dev\src\Storage\Storage.Management\Blob\EnableAzureStorageBlobLastAccessTimeTracking.cs	102	Active
Error	CS1503	Argument 1: cannot convert from 'Microsoft.Azure.Management.Storage.Models.RestorePolicyProperties' to 'Azure.ResourceManager.Storage.Models.RestorePolicyProperties'	Storage.Management	D:\code\PSH_Dev\src\Storage\Storage.Management\Blob\EnableAzureStorageBlobRestorePolicy.cs	121	Active
Error	CS1503	Argument 1: cannot convert from 'Microsoft.Azure.Management.Storage.Models.DeleteRetentionPolicy' to 'Azure.ResourceManager.Storage.Models.DeleteRetentionPolicy'	Storage.Management	D:\code\PSH_Dev\src\Storage\Storage.Management\Blob\EnableAzureStorageContainerDeleteRetentionPolicy.cs	118	Active
Error	CS1061	'GetAzStorageBlobServicePropertyCommand' does not contain a definition for 'StorageClientTrack2' and no accessible extension method 'StorageClientTrack2' accepting a first argument of type 'GetAzStorageBlobServicePropertyCommand' could be found (are you missing a using directive or an assembly reference?)	Storage.Management	D:\code\PSH_Dev\src\Storage\Storage.Management\Blob\GetAzureStorageBlobServiceProperties.cs	103	Active
Error	CS1503	Argument 1: cannot convert from 'Microsoft.Azure.Management.Storage.Models.DeleteRetentionPolicy' to 'Azure.ResourceManager.Storage.Models.DeleteRetentionPolicy'	Storage.Management	D:\code\PSH_Dev\src\Storage\Storage.Management\Blob\DisableAzureStorageBlobDeleteRetentionPolicy.cs	116	Active
Error	CS1503	Argument 1: cannot convert from 'Microsoft.Azure.Management.Storage.Models.DeleteRetentionPolicy' to 'Azure.ResourceManager.Storage.Models.DeleteRetentionPolicy'	Storage.Management	D:\code\PSH_Dev\src\Storage\Storage.Management\Blob\DisableAzureStorageContainerDeleteRetentionPolicy.cs	114	Active
Error	CS1061	'UpdateAzStorageBlobServicePropertyCommand' does not contain a definition for 'StorageClientTrack2' and no accessible extension method 'StorageClientTrack2' accepting a first argument of type 'UpdateAzStorageBlobServicePropertyCommand' could be found (are you missing a using directive or an assembly reference?)	Storage.Management	D:\code\PSH_Dev\src\Storage\Storage.Management\Blob\UpdateAzureStorageBlobServiceProperties.cs	188	Active
Error	CS1061	'UpdateAzStorageBlobServicePropertyCommand' does not contain a definition for 'StorageClientTrack2' and no accessible extension method 'StorageClientTrack2' accepting a first argument of type 'UpdateAzStorageBlobServicePropertyCommand' could be found (are you missing a using directive or an assembly reference?)	Storage.Management	D:\code\PSH_Dev\src\Storage\Storage.Management\Blob\UpdateAzureStorageBlobServiceProperties.cs	192	Active
Error	CS1503	Argument 1: cannot convert from 'Microsoft.Azure.Management.Storage.Models.CorsRules' to 'System.Collections.Generic.IList<Azure.ResourceManager.Storage.Models.CorsRule>'	Storage.Management	D:\code\PSH_Dev\src\Storage\Storage.Management\Models\PSFileServiceProperties.cs	51	Active
Error	CS1503	Argument 1: cannot convert from 'Microsoft.Azure.Management.Storage.Models.DeleteRetentionPolicy' to 'Azure.ResourceManager.Storage.Models.DeleteRetentionPolicy'	Storage.Management	D:\code\PSH_Dev\src\Storage\Storage.Management\Models\PSFileServiceProperties.cs	52	Active
Error	CS0266	Cannot implicitly convert type 'System.Collections.Generic.IList<Azure.ResourceManager.Storage.Models.CorsRule>' to 'Microsoft.Azure.Management.Storage.Models.CorsRules'. An explicit conversion exists (are you missing a cast?)	Storage.Management	D:\code\PSH_Dev\src\Storage\Storage.Management\Models\PSFileServiceProperties.cs	59	Active
Error	CS0029	Cannot implicitly convert type 'Azure.ResourceManager.Storage.Models.DeleteRetentionPolicy' to 'Microsoft.Azure.Management.Storage.Models.DeleteRetentionPolicy'	Storage.Management	D:\code\PSH_Dev\src\Storage\Storage.Management\Models\PSFileServiceProperties.cs	60	Active

**Comment by yifanz0** [comment]
@blueww Can you try to pull the code and build again? Sorry I forgot to add changes of src/Storage/Storage.Management/Blob/StorageBlobBaseCmdlet.cs in this PR, and to exclude a bunch of other classes from the csproj file.

**Review by blueww — APPROVED** [review]
Some blob service properties cmdlet still not enabled on track2 (disable/enable-* ones), so can't test all properties. 

Do you mind to add these cmdlets together to this PR, or we can also test them in the next PR for them.

**Comment by yifanz0** [comment]
@blueww Yes definitely. Just added enable-* and disable-* cmdlets to this PR.

**Review by blueww — APPROVED** [review]
LGTM

**Pull request merged**
